#!/usr/bin/env python3
"""Regenerate vendor/libYaft/glyph.h from Terminus BDF files.

Usage: gen-glyphs.py <normal.bdf> <bold.bdf> <out glyph.h>
The bitmap rows are BDF hex rows verbatim (MSB-first, byte-padded), which is
exactly the layout yaft indexes with (bdfPadding + CELL_WIDTH - 1 - w).
Used to swap the built-in 16x32 font for Terminus 12x24 (ter-u24n/b.bdf).
"""
import sys

def parse_bdf(path):
    glyphs, enc, rows, in_bitmap, w, h = {}, None, [], False, None, None
    for line in open(path):
        line = line.strip()
        if line.startswith("FONTBOUNDINGBOX "):
            _, w, h, *_ = line.split()
            w, h = int(w), int(h)
        elif line.startswith("ENCODING "):
            enc = int(line.split()[1])
        elif line == "BITMAP":
            in_bitmap, rows = True, []
        elif line == "ENDCHAR":
            if enc is not None and 0 <= enc < 0x10000:
                assert len(rows) == h, (enc, len(rows))
                glyphs[enc] = rows
            enc, in_bitmap = None, False
        elif in_bitmap:
            rows.append(int(line, 16))
    return glyphs, w, h

def emit(name, glyphs):
    out = [f"static const struct glyph_t {name}[] = {{"]
    for code in sorted(glyphs):
        rows = ", ".join(f"0x{r:X}" for r in glyphs[code])
        out.append(f"  {{ {code}, 1, {{ {rows} }} }},")
    out.append("};")
    return "\n".join(out)

normal, W, H = parse_bdf(sys.argv[1])
bold, _, _ = parse_bdf(sys.argv[2])
with open(sys.argv[3], "w") as f:
    f.write(f"""/* Generated by tools/gen-glyphs.py from Terminus {W}x{H} BDFs,
 * Copyright (C) 2020 Dimitar Toshkov Zhekov, SIL Open Font License 1.1. */
struct glyph_t {{
  uint32_t code;
  uint8_t width;
  uint32_t bitmap[{H}];
}};

enum {{ CELL_WIDTH = {W}, CELL_HEIGHT = {H} }};

""")
    f.write(emit("glyphs", normal))
    f.write("\n\n")
    f.write(emit("bold_glyphs", bold))
    f.write("\n")
print(f"wrote {sys.argv[3]}: {len(normal)}+{len(bold)} glyphs, cell {W}x{H}")
