#!/usr/bin/env python3
"""Turn cropped xochitl icon PNGs into 1-bit Icon consts for src/icons.rs.

The M6 fidelity pass crops each toolbar glyph out of a `make ref`
screenshot (the toolbar renders at a fixed size, so the crop is already at
final resolution), drops the crops in assets/icons-ref/<name>.png, and runs
this to emit row-packed 1-bit tables that draw_icon can stamp verbatim —
pixel-faithful by construction, no polyline tracing error.

Usage: python3 tools/icon-gen.py assets/icons-ref -o src/icons_bitmap.rs
"""
import argparse
import glob
import os
import struct
import sys
import zlib


def load_gray(path):
    d = open(path, "rb").read()
    assert d[:8] == b"\x89PNG\r\n\x1a\n", path
    pos, idat, w, h, ctype = 8, b"", 0, 0, 0
    while pos < len(d):
        ln = struct.unpack(">I", d[pos:pos + 4])[0]
        tag = d[pos + 4:pos + 8]
        if tag == b"IHDR":
            w, h, _, ctype = struct.unpack(">IIBB", d[pos + 8:pos + 18])
        elif tag == b"IDAT":
            idat += d[pos + 8:pos + 8 + ln]
        pos += 12 + ln
    raw = zlib.decompress(idat)
    ch = {0: 1, 2: 3, 6: 4, 4: 2}[ctype]
    stride = w * ch
    out = bytearray(w * h)
    prev = bytearray(stride)
    p = 0
    for y in range(h):
        ft = raw[p]; p += 1
        line = bytearray(raw[p:p + stride]); p += stride
        for i in range(stride):
            a = line[i - ch] if i >= ch else 0
            b = prev[i]
            c = prev[i - ch] if i >= ch else 0
            if ft == 1:
                line[i] = (line[i] + a) & 255
            elif ft == 2:
                line[i] = (line[i] + b) & 255
            elif ft == 3:
                line[i] = (line[i] + ((a + b) >> 1)) & 255
            elif ft == 4:
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pr = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 255
        for x in range(w):
            out[y * w + x] = line[x * ch]
        prev = line
    return w, h, out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dir")
    ap.add_argument("-o", "--out", default="src/icons_bitmap.rs")
    ap.add_argument("--threshold", type=int, default=128)
    a = ap.parse_args()

    pngs = sorted(glob.glob(os.path.join(a.dir, "*.png")))
    if not pngs:
        sys.exit(f"no PNGs in {a.dir} — crop toolbar glyphs there first")

    lines = ["// GENERATED by tools/icon-gen.py — do not edit by hand.",
             "// 1-bit row-packed toolbar glyphs cropped from real xochitl.",
             "pub struct Bitmap { pub w: i32, pub h: i32, pub bits: &'static [u8] }",
             ""]
    for png in pngs:
        w, h, gray = load_gray(png)
        name = os.path.splitext(os.path.basename(png))[0].upper()
        row_bytes = (w + 7) // 8
        packed = bytearray(row_bytes * h)
        for y in range(h):
            for x in range(w):
                if gray[y * w + x] < a.threshold:  # dark = ink
                    packed[y * row_bytes + (x >> 3)] |= 0x80 >> (x & 7)
        body = ", ".join(str(b) for b in packed)
        lines.append(f"pub const ICON_{name}: Bitmap = Bitmap {{ w: {w}, h: {h}, "
                     f"bits: &[{body}] }};")
    with open(a.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"icon-gen: {len(pngs)} icons -> {a.out}")


if __name__ == "__main__":
    main()
